In [2]:
import cv2

In [3]:

img = cv2.imread("images/img1.jpg")  # reads image
cv2.imshow("Image 1",img)  # shows image
cv2.waitKey(0)  # image frame wait time in milliseconds, or 0 for any key press
cv2.destroyWindow("Image 1")  # only one window close

In [4]:
img2 = cv2.imread("images/img2.jpg")  
cv2.imshow("Image 2",img2)  
cv2.imshow("Image 1",img)
cv2.waitKey(0)  
cv2.destroyAllWindows()  # all windows close

# # for destroying specific window
# cv2.destroyWindow("Image 1")

In [5]:
# resize image
resized_img = cv2.resize(img2,(500, 400))  # width 500 and height 400
cv2.imshow("Image 3",resized_img)
cv2.waitKey(0) 
cv2.destroyWindow("Image 3")

## Showing multiple images in slideshow

In [6]:
import numpy as np

image_in_arr = np.array(img)
print(image_in_arr)

[[[247 228 220]
  [247 228 220]
  [247 228 220]
  ...
  [ 30  90 136]
  [ 28  88 134]
  [ 26  86 132]]

 [[247 228 220]
  [247 228 220]
  [247 228 220]
  ...
  [ 30  90 136]
  [ 28  88 134]
  [ 26  86 132]]

 [[247 228 220]
  [247 228 220]
  [247 228 220]
  ...
  [ 31  91 137]
  [ 29  89 135]
  [ 27  87 133]]

 ...

 [[ 49 140 215]
  [ 49 140 215]
  [ 49 140 215]
  ...
  [ 50 148 218]
  [ 50 148 218]
  [ 49 147 217]]

 [[ 48 139 214]
  [ 48 139 214]
  [ 48 139 214]
  ...
  [ 51 147 217]
  [ 51 147 217]
  [ 50 146 216]]

 [[ 47 138 213]
  [ 47 138 213]
  [ 47 138 213]
  ...
  [ 51 146 216]
  [ 51 146 216]
  [ 50 145 215]]]


In [7]:
# joining two arrays horizontally
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
joinedHoriz= np.hstack((arr1,arr2))
print(joinedHoriz)

[1 2 3 4 5 6 7 8]


## **Joining Images**

In [8]:
# Joining two images horizontally 
img1 = cv2.resize(cv2.imread("images/img1.jpg"),(300,500))
img2 = cv2.resize(cv2.imread("images/img2.jpg"), (300,500))
horiz_joined = np.hstack((img1,img2))
cv2.imshow("Horizontally Joined Image",horiz_joined)
cv2.waitKey(0)
cv2.destroyWindow("Horizontally Joined Image")

In [9]:
# Joining two images Vertically 
img1 = cv2.resize(cv2.imread("images/img3.jpeg"),(250,200))
img2 = cv2.resize(cv2.imread("images/img4.jpg"), (250,200))  # width 250 and height 300
vert_joined = np.vstack((img1,img2))
cv2.imshow("Vertically Joined Image",vert_joined)
cv2.waitKey(0)
cv2.destroyWindow("Vertically Joined Image")

## **Showing multiple images in a single frame**


In [10]:
img1 = cv2.resize(cv2.imread("images/img1.jpg"),(250,200))
img2 = cv2.resize(cv2.imread("images/img2.jpg"), (250,200))
row1 = np.hstack((img1,img2))

img3 = cv2.resize(cv2.imread("images/img3.jpeg"),(250,200))
img4 = cv2.resize(cv2.imread("images/img4.jpg"), (250,200))
row2 = np.hstack((img3,img4))

# now joining both rows in v stack
slideshow = np.vstack((row1,row2))

cv2.imshow("Slideshow",slideshow)
cv2.waitKey(0)
cv2.destroyWindow("Slideshow")

## **Making Slideshow** 

In [ ]:
import os

name_list = os.listdir("images")  # A list of filenames (strings) in that directory.
name_list

for file in name_list:
    img_path = os.path.join("images",file)
    print(img_path)
    img =cv2.resize(cv2.imread(img_path),(350,400))
    cv2.imshow("Slideshow",img)
    # cv2.waitKey(2000)  # time to change the frame in milliseconds
    cv2.waitKey(0)
    
cv2.destroyAllWindows()


images\img1.jpg
images\img2.jpg
images\img3.jpeg
images\img4.jpg
